### ISSUE TITLE
Cyrillic fonts for the 12864 LCD

### ISSUE THREAD

**Issue by iley** [iley/kamaji#12]
Find cyrillic fonts for the new graphic display we are going to use.

[The display](https://www.aliexpress.com/item/Free-shipping-128-64-DOTS-LCD-module-5V-blue-screen-12864-LCD-with-backlight-ST7920-Parallel/2046467063.html) is commonly referred to as 12864 (i.e. 128x64) and uses an ST7920 controller. It can work in either parallel or serial mode, we are going to use serial.

There is a graphics library with unicode support for such displays: [olikraus/u8g2](https://github.com/olikraus/u8g2) (see [tutorial](https://github.com/olikraus/u8g2/wiki/setup_tutorial)).
There is also a [video tutorial](https://www.youtube.com/watch?v=L8_LqltPppI).

**Comment by EgorKulikov** [comment]
Done
